# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole survey
# Set your firebase account in _data/firebase.yml (see also the readme)
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: smelly cat victim
email: jing042323@163.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎各位受害闲鱼卖家提供骗子买家的地址、账号、骗人手段等信息，给他人提供防范信息的同时，也为自己维权添砖加瓦！加油，团结就是力量！！
baseurl: "https://jing042323.github.io/smelly-fish/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

# GoogleAnalytics
ga: ""

collections:
  pages:
    output: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
